package com.ingresse.sdk.v2.services

import retrofit2.Response
import retrofit2.http.Field
import retrofit2.http.FormUrlEncoded
import retrofit2.http.Header
import retrofit2.http.POST
import retrofit2.http.Query

interface SecurityService {

    /**
     * Execute MFA code validation
     *
     * @param otpCode - code generated by MFA app
     * @param code - code generated by MFA app
     * @param device - current device
     */
    @FormUrlEncoded
    @POST("/mfa/verify")
    suspend fun validateMFACode(
        @Query("apikey") apikey: String,
        @Query("usertoken") userToken: String,
        @Field("otpCode") otpCode: String,
        @Header("X-INGRESSE-OTP") code: String? = null,
    ): Response<String>
}