package com.ingresse.sdk.model.response

data class TransactionDetailsJSON(
    val id: String? = "",
    val status: String? = "",
    val transactionId: String? = "",
    val operatorId: String? = "",
    val salesgroupId: Int? = 0,
    val app_id: Int? = -1,
    val paymenttype: String? = "",
    val paymentoption: String? = "",
    val paymentdetails: String? = "",
    val creditCard: PaymentCardJSON?,
    val totalPaid: Double? = 0.0,
    val sum_up: Double? = 0.0,
    val paymentTax: Double? = 0.0,
    val interest: Int? = 0,
    val taxToCostumer: Int? = 0,
    val installments: Int? = 0,
    val creationdate: String? = "",
    val modificationdate: String? = "",
    val customer: UserDataJSON?,
    val event: TransactionEventJSON?,
    val session: TransactionSessionJSON?,
    val bankbillet_url: String? = "",
    val token: String? = "",
    val basket: TransactionBasketJSON?,
    val refund: RefundJSON?,
    val hasRefund: Boolean? = refund != null)