package com.ingresse.sdk.model.response

data class TransactionListJSON(
    val id: String? = "",
    val paymentoption: String? = "",
    val paymenttype: String? = "",
    val installments: String? = "",
    val bankbillet_url: String? = "",
    val paymentdetails: String? = "",
    val document: String? = "",
    val transactionId: String? = "",
    val token: String? = "",
    val status: String? = "",
    val totalOrder: String? = "",
    val totalPaid: String? = "",
    val sum_up: String? = "",
    val paymentTax: String? = "",
    val interest: String? = "",
    val app_id: String? = "",
    val postbackUrl: String? = "",
    val creationdate: String? = "",
    val modificationdate: String? = "",
    val operatorId: String? = "",
    val salesgroupId: String? = "",
    val creditCard: String? = "",
    val customer: TransactionUserJSON?,
    val event: TransactionEventJSON?,
    val session: TransactionSessionJSON?,
    val salesgroup: TransactionSalesGroupJSON?,
    val operator: TransactionUserJSON?)