name: Run Tests
on: [push]
jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Run Lint
      run: ./gradlew lint
    - uses: actions/upload-artifact@v1
      with:
        name: lint-report
        path: ./sdk/build/reports/lint-results.html
    - name: Gradle test
      run: ./gradlew test